#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo
echo "Susie OS"
echo "Wow, such a cool market..."
echo "now where's my hamburger? 😭"
echo

exec /bin/sh
